### ISSUE TITLE
Problems with Vitakinetic powers and Strange Crystals (or awakening) since today update (main version)

### ISSUE THREAD

**Issue by Meriados1994** [Standing-Storm/MindOverMatter#20]
After last update, when I cast staunch wounds I don't get anything in my inventory, no more Vitakinetic bandages to use, and when I cast Wakeful rest i still get sleep deprived even if it solves the tiredness problem.

Don't know if something else changed, but I managed to find strange crystals since I started trying the mod, but after 0.6 (I think) I didn't manage to find a single one, nor gaining a new school of powers from the portal storms, even staying for whole portal storms duration outside.

**Comment by Standing-Storm** [comment]
I can't replicate the problem with Wakeful Rest on latest experimental, but I can confirm something is wrong with Staunch Wounds. It looks like the minimum item spawn defaults to 0 instead of 1 now, but going in and defining that explicitly solves it so I'll add that to the next release.

I did reduce the odds of portal storms awakening you so every storm isn't a reliable awakening but I actually increased the odds of strange crystals dropping, so I think that part is just bad luck. 

Could you provide more documentation for your problem with Wakeful Rest, please? When you get up to Sleep Deprivation and channel it, your sleep deprivation doesn't go away? What does your Sleep Deprivation level read under your needs before and after using it (Debug -> Player -> Edit Player/NPC -> Set Needs)?

**Comment by Meriados1994** [comment]
Okay, I managed to mess up a bit with it, Wakeful Rest works as intended I think, it's just that tiredness and sleepiness accumulate at different rates and Wakeful Rest removes way less sleep deprivation than tiredness, it's just a matter of spamming it once or twice after tiredness goes to 0.

I think I had that perception about the storm because your change happened while portal storms durations got reduced (maybe? I am going on intuition about what I'm seeing testing this)

If I wasn't very stupid I'd check, but where am I supposed to get the crystals properly? I used to find them in labs but I still didn't find any, even in the "-10 lost floor" lab.

Also, if I'm surrounded by 9 solid tiles like walls but no roof over me, do I still count as being in a portal storm?

Edit: I tried your last version with the min charges changed for Staunch Wounds but i'm still getting no bandages, I still got low level powers tho.

Edit 2: It now works properly, I'm getting the bandages but still no other schools unlocked after 3 portal storms

**Comment by Standing-Storm** [comment]
> I think I had that perception about the storm because your change happened while portal storms durations got reduced (maybe? I am going on intuition about what I'm seeing testing this)

I think portal storm duration is now affected by the ps_str global variable, which means that they start very short and get longer and longer as more of them happen, which means I'll probably need to do some more changes to the formula for awakening during a storm or move forward my idea to make it a vitamin like mutagen already is. 

> If I wasn't very stupid I'd check, but where am I supposed to get the crystals properly? I used to find them in labs but I still didn't find any, even in the "-10 lost floor" lab.

They drop from psychic ferals, are sometimes found in research facilities and distorted labs, and I'm adding a new area now where they'll be more common too. The latest version (the in-progress one you downloaded) also has some Project PHAVIAN scientists mixed in among the regular XEDRA scientists that carry psionics research material and might have them.

> Also, if I'm surrounded by 9 solid tiles like walls but no roof over me, do I still count as being in a portal storm?

Yes. You can even just drag 9 bookcases into a cluster around yourself

> Edit 2: It now works properly, I'm getting the bandages but still no other schools unlocked after 3 portal storms

Well, I'm glad that bug is fixed!
