### ISSUE TITLE
Quell Fire need a little bit of rework

### ISSUE THREAD

**Issue by Lalomb0000** [Standing-Storm/MindOverMatter#29]
For now Quell Fire calls for a generic spray of extinguisher mist, which is fine, that's the point of a fire extinguisher, but it looks odd and it's really spammy.

I need to use upwards of 5 to 15 uses to kill a regular size fire spread, besides counting the times when the cloud doesn't appear on the spots that needs to.

The spell needs to self replicate for a couple of seconds so that, hits all the fire spots and, kills bigger fires all at once, so it doesn't have to be spammed.

Don't know what may be your opinions on the matter or even if it's possible, but that's the easiest solution I can contemplate

**Comment by Lalomb0000** [comment]
Love the mod

**Comment by Standing-Storm** [comment]
Unfortunately my original idea--use the existing "remove_field" effect--was a non-starter because remove_field isn't "remove all fields of the appropriate type from within the AoE," it's "go through the entire AoE area, pick one specific example of a field, and remove that one field," making using that a non-starter. And the fire extinguisher mist's effects are hardcoded, so I can't create another field that spreads easier that would have the same effects. I could increase the starting intensity, but it won't spread fast enough to fill every tile. 

There's a hacky nonsense solution I found that will at least allow the central core to last a few turns that I could implement, though, so at least the exact area you target will definitely be free of flames.
